---
vmware_name:          
vmware_folder:               
vmware_template:                    
vmware_cluster: DevOps-Cluster                   
vmware_datastore: VxRail-Virtual-SAN-Datastore-0e65a757-a56b-446d-90e0-36664d45baef               
vmware_datacenter: DevOps              
vmware_disk_size_gb: 100                       
vmware_disk_type: thin                       
vmware_memory_mb: 16384                         
vmware_number_of_cpus: 8                   
vmware_number_cpu_cores_per_socket: 1
vmware_networks_name: 
vmware_ip: 
vmware_netmask: 255.255.255.0
vmware_gateway: 
vmware_ip_type: static
domain: exch2013.local
hostname: 
dns_servers: 10.2.100.96