---
- name: Check the VM existence 
  community.vmware.vmware_guest_info:
    hostname: '{{ lookup("env", "VMWARE_HOST") }}' 
    username: '{{ lookup("env", "VMWARE_USER") }}'
    password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
    datacenter: "{{ vmware_datacenter }}" 
    validate_certs: false
    name: "{{ vmware_name }}"
    name_match: "first" 
  delegate_to: localhost
  register: vm_info
  ignore_errors: true

- name: JSON query
  set_fact:
    query_vmname: "results[*].instance.hw_name"  

- name: Set VM status 
  set_fact:
    vm_hostname: "{{ vm_info | json_query (query_vmname) | string }}"

- ansible.builtin.debug:
    msg: 
      - "{{ vm_hostname }}" 

